//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess_master_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Online_ChessEntities : DbContext
    {
        public Online_ChessEntities()
            : base("name=Online_ChessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OnlineChess> OnlineChesses { get; set; }
        public virtual DbSet<ChessResultDetail> ChessResultDetails { get; set; }
        public virtual DbSet<ChessResultMaster> ChessResultMasters { get; set; }
    }
}
