//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess_master_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChessResultDetail
    {
        public int ChessResultDetailsID { get; set; }
        public Nullable<int> ResultMasterID { get; set; }
        public Nullable<System.DateTime> Inserteddate { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ChessResultMaster ChessResultMaster { get; set; }
        public virtual OnlineChess OnlineChess { get; set; }
    }
}
